import datetime
from sqlalchemy import Column, Integer, String, Float, Boolean, DateTime, ForeignKey, Date
from sqlalchemy.orm import relationship
from backend.app.core.database import Base

class User(Base):
    """
    User model representing registered users.
    Stores authentication and profile information.
    """
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    full_name = Column(String, nullable=True)
    profile_picture = Column(String, nullable=True)  # Store filename/path of profile picture
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    transactions = relationship("Transaction", back_populates="user", cascade="all, delete-orphan")
    budgets = relationship("Budget", back_populates="user", cascade="all, delete-orphan")
    predictions = relationship("Prediction", back_populates="user", cascade="all, delete-orphan")
    reports = relationship("Report", back_populates="user", cascade="all, delete-orphan")
    savings_goals = relationship("SavingsGoal", back_populates="user", cascade="all, delete-orphan")


class Category(Base):
    """
    Category model representing classification labels for transactions.
    Default categories: Food, Travel, Shopping, Bills, Medical, Entertainment, Education, Others.
    """
    __tablename__ = "categories"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, unique=True, index=True, nullable=False)
    is_default = Column(Boolean, default=True)


class Transaction(Base):
    """
    Transaction model representing spending or income.
    Transactions can be added manually or parsed from CSV files.
    """
    __tablename__ = "transactions"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    date = Column(Date, nullable=False)  # Stored as python date
    description = Column(String, nullable=False)
    amount = Column(Float, nullable=False)
    type = Column(String, nullable=False)  # 'income' or 'expense'
    category = Column(String, nullable=False, default="Others")  # Selected from Category list
    
    # ML Outputs
    is_anomaly = Column(Boolean, default=False)  # Flagged by Isolation Forest
    anomaly_score = Column(Float, nullable=True)
    
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    # Relationships
    user = relationship("User", back_populates="transactions")


class Budget(Base):
    """
    Budget model representing spending targets set by users.
    """
    __tablename__ = "budgets"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    category = Column(String, nullable=False)  # E.g., 'Food', or 'Total'
    limit_amount = Column(Float, nullable=False)
    month = Column(String, nullable=False)  # Format 'YYYY-MM', e.g., '2026-07'
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    # Relationships
    user = relationship("User", back_populates="budgets")


class Prediction(Base):
    """
    Prediction model storing monthly expense predictions generated by ML models.
    """
    __tablename__ = "predictions"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    target_month = Column(String, nullable=False)  # Format 'YYYY-MM', e.g., '2026-08'
    predicted_amount = Column(Float, nullable=False)
    model_used = Column(String, nullable=False)  # E.g., 'Linear Regression' or 'Random Forest'
    
    # Performance metrics of the prediction run
    mae = Column(Float, nullable=True)
    rmse = Column(Float, nullable=True)
    r2_score = Column(Float, nullable=True)
    
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    # Relationships
    user = relationship("User", back_populates="predictions")


class Report(Base):
    """
    Report model storing records of generated PDF reports.
    """
    __tablename__ = "reports"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    name = Column(String, nullable=False)  # E.g., 'Financial_Report_July_2026.pdf'
    file_path = Column(String, nullable=False)  # Path to download PDF
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    # Relationships
    user = relationship("User", back_populates="reports")


class SavingsGoal(Base):
    """
    SavingsGoal model representing targeted savings targets (e.g. ₹50,000 for a laptop).
    """
    __tablename__ = "savings_goals"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    name = Column(String, nullable=False)
    target_amount = Column(Float, nullable=False)
    current_amount = Column(Float, default=0.0)
    target_date = Column(Date, nullable=True)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    # Relationships
    user = relationship("User", back_populates="savings_goals")
